=== januarydev/MissionControl/src-tauri/config.schema.json
{
  "$schema":"https://json-schema.org/draft-07/schema#",
  "properties": {
    "base_rate_hz": {
      "description": "Simulation base step rate, hz",
      "type": "integer",
      "exclusiveMinimum": 0
    },
    "frontend_update_rate_hz": {
      "description": "Frontend data update rate, hz",
      "type": "integer",
      "exclusiveMinimum": 0
    },
    "initial_time": {
      "description": "Simulation starting time/date (restricted to J2000 so no dates before Jan 1 2000 @ noon)",
      "type": "object",
      "properties": {
        "year": {
          "description": "CE year, must be 2000 or later",
          "type": "integer",
          "minimum": 2000,
          "maximum": 2150
        },
        "month": {
          "description": "Month of year, 1-12",
          "type": "integer",
          "minimum": 1,
          "maximum": 12
        },
        "day": {
          "description": "Day of month, will not restrict you to legal days (i.e., 30th of Feb will not be caught), so be careful!",
          "type": "integer",
          "minimum": 1,
          "maximum": 31
        },
        "hour": {
          "description": "Hour of day, 24hour-based (0-23)",
          "type": "integer",
          "minimum": 0,
          "maximum": 23
        },
        "minute": {
          "description": "Minute of hour, 0-based",
          "type": "integer",
          "minimum": 0,
          "maximum": 59
        },
        "second": {
          "description": "Second of minute, 0-based",
          "type": "number",
          "minimum": 0,
          "exclusiveMaximum": 60
        }
      },
      "required": [
        "year",
        "month",
        "day",
        "hour",
        "minute",
        "second"
      ]
    },
    "unfocused_bodies": {
      "description": "Array of bodies to include in background simulation EXCLUDING EARTH (always included by default)",
      "type":"array",
      "items": {
        "type":"object",
        "$ref": "#/$defs/body"
      }
    },
    "focused_body": {
      "description": "Description of the body that can be controlled with commands and is focused for telemetry.",
      "type":"object",
      "$ref": "#/$defs/body"
    }
  },
  "required": [
    "base_rate_hz",
    "frontend_update_rate_hz",
    "initial_time",
    "unfocused_bodies",
    "focused_body"
  ],
  "$defs": {
    "body": {
      "properties": {
        "name": {
          "description": "Body name",
          "type": "string"
        },
        "mass_kg": {
          "description": "Body mass, kg",
          "type": "number",
          "exclusiveMinimum": 0
        },
        "position_eci_km": {
          "description": "Position of the body at simulation start in J2000 ECI, km",
          "type": "array",
          "minItems": 3,
          "maxItems": 3,
          "items": {"type": "number"}
        },
        "velocity_eci_km_s": {
          "description": "Velocity of the body at simulation start in J2000 ECI, km/s",
          "type": "array",
          "minItems": 3,
          "maxItems": 3,
          "items": {"type": "number"}
        },
        "perturbation_stats": {
          "description": "Optional parameters for perturbation models (will not include perturbation modelling for body if not present).",
          "type": "object",
          "properties": {
            "aero_drag_area_m2": {
              "description": "Effective 'cannonball' model surface area for aerodynamic drag perturbation, m^2.",
              "type": "number",
              "minimum": 0
            },
            "aero_drag_coef": {
              "description": "Dimensionless coefficient of drag for aerodynamic drag perturbation.",
              "type": "number",
              "minimum": 0
            },
            "solar_rad_pres_area_m2": {
              "description": "Effective 'cannonball' model of surface area for solar radiation pressure perturbation, m^2",
              "type": "number",
              "minimum": 0
            },
            "solar_rad_pres_coef": {
              "description": "Dimensionless coefficient of absorption for solar radiation pressure perturbation.",
              "type": "number",
              "minimum": 0
            }
          },
          "required": [
            "aero_drag_area_m2",
            "aero_drag_coef",
            "solar_rad_pres_area_m2",
            "solar_rad_pres_coef"
          ]
        }
      },
      "required": [
        "name",
        "mass_kg",
        "position_eci_km",
        "velocity_eci_km_s"
      ]
    }
  }
}

=== januarydev/MissionControl/src-tauri/config/config.json
{
  "$schema": "config.schema.json",
  "base_rate_hz": 100,
  "frontend_update_rate_hz": 1,
  "initial_time": {
    "year": 2022,
    "month": 1,
    "day": 3,
    "hour": 12,
    "minute": 0,
    "second": 0
  },
  "unfocused_bodies": [
    {
      "name": "Sun",
      "mass_kg": 1.989e+30,
      "position_eci_km": [
        3.12641188e+07,
        -1.31885928e+08,
        -5.71723857e+07
      ],
      "velocity_eci_km_s": [
        29.60534526,
        5.91568088,
        2.56335503
      ]
    },
    {
      "name": "Mars",
      "mass_kg": 641.9e+21,
      "position_eci_km": [
        -9.47912941e+07,
        -3.07465391e+08,
        -1.34305768e+08
      ],
      "velocity_eci_km_s": [
        50.76155452,
        -4.08904415,
        -2.59641757
      ]
    },
    {
      "name": "Jupiter",
      "mass_kg": 1.899e+27,
      "position_eci_km": [
        7.28873213e+08,
        -3.70425664e+08,
        -1.76398088e+08
      ],
      "velocity_eci_km_s": [
        34.11353284,
        17.75243955,
        7.52718526
      ]
    },
    {
      "name": "Moon",
      "mass_kg": 7.348e+22,
      "position_eci_km": [
        95588.51403895,
        -307826.35251934,
        -158261.2686987
      ],
      "velocity_eci_km_s": [
        1.05971864,
        0.27971128,
        0.04331688
      ]
    }
  ],
  "focused_body": {
    "name": "ISS",
    "mass_kg": 467752,
    "position_eci_km": [
      -1325.896391725290,
      5492.890955896010,
      3762.423747679220
    ],
    "velocity_eci_km_s": [
      -4.87470128630892,
      -4.10251688094599,
      4.26428812476909
    ],
    "perturbation_stats": {
      "aero_drag_area_m2": 1951,
      "aero_drag_coef": 2,
      "solar_rad_pres_area_m2": 1500,
      "solar_rad_pres_coef": 1.8
    },
    "q_inertial_to_body": [
      0,
      0,
      0.7071,
      0.7071
    ],
    "inertia_kg_m2": [
      69612976,
      4686018,
      2919236,
      4686018,
      35145372,
      -2472870,
      2919236,
      -2472870,
      96574584
    ]
  }
}
